name: timeout
on:
    push:

jobs:
    timeout:
        runs-on: ubuntu-latest
        steps:
        - name: loop
          run: |
            count=0
            while true; do
                echo "seconds: $count"
                count=$((count+1))
                sleep 1
            done
          timeout-minutes: 1
        - name: echo
          run: echo hello
